### ISSUE TITLE
db.open() function returns Zero

### ISSUE THREAD

**Issue by himanshu-hearthacker** [firebull/arduino-edb#10]
I want to create table only once in life time. I am using this function to detect if table exists or not. But this function always returns me 0(Zero) every time even if table exists or not.
I updated code to this library.
https://github.com/jwhiddon/EDB/blob/master/EDB.cpp

```C++
EDB_Status result = db.open(0);
if (result == EDB_ERROR) {
        Serial.println("Creating DB " + String(0));
        db.create(0, TABLE_SIZE, sizeof(LogEvent));
} else {
    Serial.println(result);
}
```

**Comment by firebull** [comment]
Where do you create the table? How do you create it? Show the code, please.

**Comment by himanshu-hearthacker** [comment]
I have written the above code in setup() function. In code i am crating table using the following code.
 db.create(0, TABLE_SIZE, sizeof(LogEvent));

the open function is --

```C++
EDB_Status EDB::open(unsigned long head_ptr) {
  EDB_head_ptr = head_ptr;
  // Thanks to Steve Kelly for the next line... 
  EDB_table_ptr = sizeof(EDB_Header) + EDB_head_ptr; // this line was originally missing in the downloaded library
  readHead();
   if (EDB_head.flag == EDB_FLAG){
      return EDB_OK;
  } else {
      return EDB_ERROR;
  }  
}
```
Please see the link
https://drive.google.com/open?id=1jrDt4P1KmJ3P4v9rAbTjN5R7cYzivAPn

**Comment by firebull** [comment]
OMG =)

Of course it return zero. 

result - is EDB_Status enum:

``` C++
enum EDB_Status {
                      EDB_OK,
                      EDB_ERROR,
                      EDB_OUT_OF_RANGE,
                      EDB_TABLE_FULL
                    };
```

Serial.print() outputs it as integer, because also this enum can be created as:

``` C++
enum EDB_Status {
                      EDB_OK = 0,
                      EDB_ERROR = 1,
                      EDB_OUT_OF_RANGE = 2,
                      EDB_TABLE_FULL = 3
                    };
```

**Comment by himanshu-hearthacker** [comment]
That's correct but as you can see in the image given in the link above, whenever i run the code i truncate the table using deleteAll() function. Since my table does not exist, i always moves to else condition without creating the table.

**Comment by firebull** [comment]
That's because you've already created the db. It searches for the table header, it founds it, so table is created.

If you want to create db each time at start, you must not simply open it. You must CREATE it.

use 

```C++
EDB_Status result = db.create(0, TABLE_SIZE, sizeof(logEvent));
```

And I am VERY sorry, but looks like you have not enough experience in C++, right? I know, it is very hard to write code using C/C++ after javascript, but you'd better get know some principles of C++. I am sorry one more time =))

**Comment by himanshu-hearthacker** [comment]
I make a comment to the particular line in the code that you mentioned . I want to create the DB only once as Creating DB again and again with same address deletes all my stored data.

**Comment by firebull** [comment]
Ok. So I do not understand the problem.

The code at your first message is correct. It tries to open the DB. If it is not found, it creates it. Thats all.

**Comment by himanshu-hearthacker** [comment]
i truncate the table every time when code restarts but The function db.open() returns  EDB_OK  without creating the table or might be deleteAll() function only delete the data not the table. I have written the function to print the values of EDB header return by db.open() function.
In the image you can see even after deleting the table, the function db.open() returns EDB_OK header.
The function db.open()  does not EDB_ERROR even after truncating the table. It always return EDB_OK.
Please look at the image..
https://drive.google.com/open?id=17_eBakgW5xHCsBQoosIRMdaBRM180ar_

**Comment by firebull** [comment]
I really do not understand, what do you want to do.

There is no all the data clean. Deletion is just header rewriting function. If you delete last record it just lower recordNumber. If you delete some other record, it moves records to it place and changes the record number.

If you wanna FULLY delete DB and clean all the data, than you have to manually rewrite place where DB is stored by 0x00.

What is your task?

**Comment by himanshu-hearthacker** [comment]
https://drive.google.com/open?id=17_eBakgW5xHCsBQoosIRMdaBRM180ar_

**Comment by himanshu-hearthacker** [comment]
[https://drive.google.com/open?id=17_eBakgW5xHCsBQoosIRMdaBRM180ar_]

**Comment by himanshu-hearthacker** [comment]
I am sorry about that, i was facing some issue with the link. As you can see in the image given in the link, I truncate the table every time i restart the code but db,open() function always gives EDB_OK as return even if table exist or not. I have written a function to show value of enum.

My only aim is just to create the table only once in lifetime.

https://drive.google.com/file/d/17_eBakgW5xHCsBQoosIRMdaBRM180ar_/view

**Comment by firebull** [comment]
Again. What is the `deleteAll()` function? What is it doing?

Second. You must rewrite header of the DB with `0x00` if you want to delete everything.

Third. What is your task? What do you want to do in fact?

**Comment by himanshu-hearthacker** [comment]
Delete all function is:

```C++
void deleteAll()
{
  Serial.print("Truncating table...");
  db.clear();
  Serial.println("DONE");
}
```

I just want to create table if it doesn't exist but db.open() always return EDB_OK which means if the table doesn't exist it will not create the table.

**Comment by firebull** [comment]
Well, first of all. If you would take a look in `EDB.cpp` you see, that function `db.clear()` simply rewrites the header, it just recreates the DB:

```C++
// truncates the queue by resetting the internal pointers
void EDB::clear()
{
  readHead();
  create(EDB_head_ptr, EDB_head.table_size, EDB_head.rec_size);
}
```
Second. I still do not see the problem. Your code in first message is correct. It does everything right.

Look. It is hard to understand low-level working in C/C++ after PHP, Javascript and so on. But in such systems you can not do all the work like in modern computers. 

All the data are stored in binary format. So this DB is:

1. Header: TABLE_FLAG -> CURRENT_RECORDS -> RECORD_SIZE -> TABLE_SIZE
2. Record №1: Just binary data which size is RECORD_SIZE
3. Record №2: Just binary data which size is RECORD_SIZE
....... And so on

When you read the data, you read binary data and convert them to **struct** `EDB_Rec rec`.

So if you ONCE created the DB, header will ALWAYS be in place until you rewrite it by `0x00`. All the data will still be stored until you rewrite them by `0x00`.

Your code means:

- IF TABLE DOES NOT EXIST -> CREATE THE TABLE
- IF TABLE EXISTS -> READ THE HEADER AND USE THIS TABLE

**Comment by himanshu-hearthacker** [comment]
Now i got your point thanks for your help.
