### ISSUE TITLE
Can I query the database for an entry with a certain field?

### ISSUE THREAD

**Issue by DGxInfinitY** [firebull/arduino-edb#8]
I am trying to use this library to store a variable whenever a save button is pressed,  but I also what to be able to search for these when a search is entered, is there a search function available or is it possible to make one using this library?

**Comment by firebull** [comment]
Well, short answer is yes, you can do it. But that is not good idea, to search data in all DB.

In fact, this Arduino-EDB is not DataBase. It just writes number of structs one by one.

You can make cycle read one by one using **readRec** function. But if you use simple cycle it gonna be very slow. It will be a big delay. So if you will use some kind of task manager like [TaskSchedule](https://playground.arduino.cc/Code/TaskScheduler) or RealTime OS like [FreeRTOS](http://www.freertos.org/index.html) that will be ok.

**Comment by DGxInfinitY** [comment]
Ok I am in the development phase right now and would like to implement it, what would I use to do so, as you said the readRec function but how would I use that and search for specific data using the readRec function? Could you give a small bit of code with an example of this? I am sorry I am just having a heck of a time trying to find out how to do this.
Edit: Just so you know more background I am using the Teensy3.2 (which is Arduino compatible). I have it running at 120 MHz so its more than capable to take a few extra cycles for sorting and searching line by line, not to mention it doesn't need to be crazy fast.

**Comment by firebull** [comment]
Well, something like this. Simple and shortened example of one of my old projects.

It searches data in last 6 rows.

```C++
struct SensorData {
    float temp_1;
    float temp_2;
    float humidity;
    float pressure;
    char datetime[21];
    char type[2];
    unsigned long timestamp;
}
sensorData;

void searchData(){
    SensorData row;
    byte rows,
         startRow;

    if (rows > 0) {
        // Get only 6 last rows
        if (rows < 6) {
            startRow = 1;
        } else {
            startRow = rows - 6 + 1;
        }

        for (byte i = startRow; i <= rows; i++) {
            db.readRec(i, EDB_REC row);

            // Here you can do some work with row
            // Also, if you use FreeRTOS, add in last string of current cycle
            //vTaskDelay(1);
            // to unblock the task. Or it will be huge delay on big data
        }
    }
}
```

I do recommend you to use [FreeRTOS](http://www.freertos.org/index.html) or [TaskScheduler](https://playground.arduino.cc/Code/TaskScheduler). Trust me, better spend some time to learn them.
